// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Fun_Actor_Title_Show","status":true,"description":"地图上主角头顶显示称号。","parameters":{}},
{"name":"Fun_Event_Title_Show","status":true,"description":"地图上任意事件头顶显示名字。","parameters":{}},
{"name":"Fun_Item_Help_Show","status":true,"description":"菜单物品栏显示详细信息。","parameters":{}},
{"name":"Fun_Practice_Status_Show","status":true,"description":"挂机修行 地图上显示状态信息。","parameters":{}},
{"name":"Fun_Battle_Show","status":true,"description":"战斗界面修改。","parameters":{}},
{"name":"Fun_Enemy_Battler_Information","status":true,"description":"战斗场景显示敌人详细信息","parameters":{}},
{"name":"Fun_Actor_Battler_Information","status":true,"description":"战斗场景显示主角详细信息","parameters":{}}
];
